# main:
#   - name: Example Site
#     weight: 40
#     url: 'https://example.docsy.dev'
#     pre: <i class='fas fa-laptop-code'></i>
#   - name: GitHub
#     weight: 50
#     url: 'https://github.com/google/docsy/'
#     pre: <i class='fab fa-github'></i>
#     post: <span class='alert'>New!</span>
    