import React from "react";
import Link from "@docusaurus/Link";

// This file is generated by scripts/fetch-changelogs.mjs
// Falls back to empty object if not yet generated
let versions: Record<
  string,
  {
    version: string;
    description: string;
    repo: string;
    category: string;
  }
> = {};

try {
  versions = require("@site/support/changelog/_versions.json");
} catch {
  // file not generated yet — show empty table
}

interface ChangelogTableProps {
  category: string;
}

export default function ChangelogTable({
  category,
}: ChangelogTableProps): React.ReactElement | null {
  const entries = Object.entries(versions).filter(
    ([, v]) => v.category === category
  );

  if (entries.length === 0) {
    return (
      <p>
        <em>
          No changelog data available. Run{" "}
          <code>node scripts/fetch-changelogs.mjs</code> to fetch the latest
          changelogs.
        </em>
      </p>
    );
  }

  return (
    <table>
      <thead>
        <tr>
          <th>Package</th>
          <th>Version</th>
          <th>Description</th>
          <th>Links</th>
        </tr>
      </thead>
      <tbody>
        {entries.map(([name, info]) => (
          <tr key={name}>
            <td>
              <strong>{name}</strong>
            </td>
            <td>
              <code>{info.version}</code>
            </td>
            <td>{info.description}</td>
            <td>
              <Link to={`/support/changelog/${info.repo}`}>Changelog</Link>
              {" · "}
              <a
                href={`https://github.com/iNZightVIT/${info.repo}/releases`}
                target="_blank"
                rel="noopener noreferrer"
              >
                GitHub
              </a>
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}
